/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 4.0.1
 *
 * This file is not intended to be easily readable and contains a number of
 * coding conventions designed to improve portability and efficiency. Do not make
 * changes to this file unless you know what you are doing--modify the SWIG
 * interface file instead.
 * ----------------------------------------------------------------------------- */

// source: /home/tomatofaq/go/src/github.com/CoatiSoftware/SourcetrailDB-master/resources_swig/interface/sourcetraildb.i

package sourcetraildb

/*
#define intgo swig_intgo
typedef void *swig_voidp;

#include <stdint.h>


typedef long long intgo;
typedef unsigned long long uintgo;



typedef struct { char *p; intgo n; } _gostring_;
typedef struct { void* array; intgo len; intgo cap; } _goslice_;


typedef _gostring_ swig_type_1;
typedef _gostring_ swig_type_2;
typedef _gostring_ swig_type_3;
typedef _gostring_ swig_type_4;
typedef _gostring_ swig_type_5;
typedef _gostring_ swig_type_6;
typedef _gostring_ swig_type_7;
typedef _gostring_ swig_type_8;
extern void _wrap_Swig_free_sourcetraildb_d01c6fe4bdcf0ab5(uintptr_t arg1);
extern uintptr_t _wrap_Swig_malloc_sourcetraildb_d01c6fe4bdcf0ab5(swig_intgo arg1);
extern swig_intgo _wrap_DEFINITION_IMPLICIT_sourcetraildb_d01c6fe4bdcf0ab5(void);
extern swig_intgo _wrap_DEFINITION_EXPLICIT_sourcetraildb_d01c6fe4bdcf0ab5(void);
extern swig_intgo _wrap_SYMBOL_TYPE_sourcetraildb_d01c6fe4bdcf0ab5(void);
extern swig_intgo _wrap_SYMBOL_BUILTIN_TYPE_sourcetraildb_d01c6fe4bdcf0ab5(void);
extern swig_intgo _wrap_SYMBOL_MODULE_sourcetraildb_d01c6fe4bdcf0ab5(void);
extern swig_intgo _wrap_SYMBOL_NAMESPACE_sourcetraildb_d01c6fe4bdcf0ab5(void);
extern swig_intgo _wrap_SYMBOL_PACKAGE_sourcetraildb_d01c6fe4bdcf0ab5(void);
extern swig_intgo _wrap_SYMBOL_STRUCT_sourcetraildb_d01c6fe4bdcf0ab5(void);
extern swig_intgo _wrap_SYMBOL_CLASS_sourcetraildb_d01c6fe4bdcf0ab5(void);
extern swig_intgo _wrap_SYMBOL_INTERFACE_sourcetraildb_d01c6fe4bdcf0ab5(void);
extern swig_intgo _wrap_SYMBOL_ANNOTATION_sourcetraildb_d01c6fe4bdcf0ab5(void);
extern swig_intgo _wrap_SYMBOL_GLOBAL_VARIABLE_sourcetraildb_d01c6fe4bdcf0ab5(void);
extern swig_intgo _wrap_SYMBOL_FIELD_sourcetraildb_d01c6fe4bdcf0ab5(void);
extern swig_intgo _wrap_SYMBOL_FUNCTION_sourcetraildb_d01c6fe4bdcf0ab5(void);
extern swig_intgo _wrap_SYMBOL_METHOD_sourcetraildb_d01c6fe4bdcf0ab5(void);
extern swig_intgo _wrap_SYMBOL_ENUM_sourcetraildb_d01c6fe4bdcf0ab5(void);
extern swig_intgo _wrap_SYMBOL_ENUM_CONSTANT_sourcetraildb_d01c6fe4bdcf0ab5(void);
extern swig_intgo _wrap_SYMBOL_TYPEDEF_sourcetraildb_d01c6fe4bdcf0ab5(void);
extern swig_intgo _wrap_SYMBOL_TYPE_PARAMETER_sourcetraildb_d01c6fe4bdcf0ab5(void);
extern swig_intgo _wrap_SYMBOL_MACRO_sourcetraildb_d01c6fe4bdcf0ab5(void);
extern swig_intgo _wrap_SYMBOL_UNION_sourcetraildb_d01c6fe4bdcf0ab5(void);
extern swig_intgo _wrap_REFERENCE_TYPE_USAGE_sourcetraildb_d01c6fe4bdcf0ab5(void);
extern swig_intgo _wrap_REFERENCE_USAGE_sourcetraildb_d01c6fe4bdcf0ab5(void);
extern swig_intgo _wrap_REFERENCE_CALL_sourcetraildb_d01c6fe4bdcf0ab5(void);
extern swig_intgo _wrap_REFERENCE_INHERITANCE_sourcetraildb_d01c6fe4bdcf0ab5(void);
extern swig_intgo _wrap_REFERENCE_OVERRIDE_sourcetraildb_d01c6fe4bdcf0ab5(void);
extern swig_intgo _wrap_REFERENCE_TYPE_ARGUMENT_sourcetraildb_d01c6fe4bdcf0ab5(void);
extern swig_intgo _wrap_REFERENCE_TEMPLATE_SPECIALIZATION_sourcetraildb_d01c6fe4bdcf0ab5(void);
extern swig_intgo _wrap_REFERENCE_INCLUDE_sourcetraildb_d01c6fe4bdcf0ab5(void);
extern swig_intgo _wrap_REFERENCE_IMPORT_sourcetraildb_d01c6fe4bdcf0ab5(void);
extern swig_intgo _wrap_REFERENCE_MACRO_USAGE_sourcetraildb_d01c6fe4bdcf0ab5(void);
extern swig_intgo _wrap_REFERENCE_ANNOTATION_USAGE_sourcetraildb_d01c6fe4bdcf0ab5(void);
extern swig_type_1 _wrap_getVersionString_sourcetraildb_d01c6fe4bdcf0ab5(void);
extern swig_intgo _wrap_getSupportedDatabaseVersion_sourcetraildb_d01c6fe4bdcf0ab5(void);
extern swig_type_2 _wrap_getLastError_sourcetraildb_d01c6fe4bdcf0ab5(void);
extern void _wrap_clearLastError_sourcetraildb_d01c6fe4bdcf0ab5(void);
extern _Bool _wrap_open_sourcetraildb_d01c6fe4bdcf0ab5(swig_type_3 arg1);
extern _Bool _wrap_close_sourcetraildb_d01c6fe4bdcf0ab5(void);
extern _Bool _wrap_clear_sourcetraildb_d01c6fe4bdcf0ab5(void);
extern _Bool _wrap_isEmpty_sourcetraildb_d01c6fe4bdcf0ab5(void);
extern _Bool _wrap_isCompatible_sourcetraildb_d01c6fe4bdcf0ab5(void);
extern swig_intgo _wrap_getLoadedDatabaseVersion_sourcetraildb_d01c6fe4bdcf0ab5(void);
extern _Bool _wrap_beginTransaction_sourcetraildb_d01c6fe4bdcf0ab5(void);
extern _Bool _wrap_commitTransaction_sourcetraildb_d01c6fe4bdcf0ab5(void);
extern _Bool _wrap_rollbackTransaction_sourcetraildb_d01c6fe4bdcf0ab5(void);
extern _Bool _wrap_optimizeDatabaseMemory_sourcetraildb_d01c6fe4bdcf0ab5(void);
extern swig_intgo _wrap_recordSymbol_sourcetraildb_d01c6fe4bdcf0ab5(swig_type_4 arg1);
extern _Bool _wrap_recordSymbolDefinitionKind_sourcetraildb_d01c6fe4bdcf0ab5(swig_intgo arg1, swig_intgo arg2);
extern _Bool _wrap_recordSymbolKind_sourcetraildb_d01c6fe4bdcf0ab5(swig_intgo arg1, swig_intgo arg2);
extern _Bool _wrap_recordSymbolLocation_sourcetraildb_d01c6fe4bdcf0ab5(swig_intgo arg1, swig_intgo arg2, swig_intgo arg3, swig_intgo arg4, swig_intgo arg5, swig_intgo arg6);
extern _Bool _wrap_recordSymbolScopeLocation_sourcetraildb_d01c6fe4bdcf0ab5(swig_intgo arg1, swig_intgo arg2, swig_intgo arg3, swig_intgo arg4, swig_intgo arg5, swig_intgo arg6);
extern _Bool _wrap_recordSymbolSignatureLocation_sourcetraildb_d01c6fe4bdcf0ab5(swig_intgo arg1, swig_intgo arg2, swig_intgo arg3, swig_intgo arg4, swig_intgo arg5, swig_intgo arg6);
extern swig_intgo _wrap_recordReference_sourcetraildb_d01c6fe4bdcf0ab5(swig_intgo arg1, swig_intgo arg2, swig_intgo arg3);
extern _Bool _wrap_recordReferenceLocation_sourcetraildb_d01c6fe4bdcf0ab5(swig_intgo arg1, swig_intgo arg2, swig_intgo arg3, swig_intgo arg4, swig_intgo arg5, swig_intgo arg6);
extern _Bool _wrap_recordReferenceIsAmbiguous_sourcetraildb_d01c6fe4bdcf0ab5(swig_intgo arg1);
extern swig_intgo _wrap_recordReferenceToUnsolvedSymhol_sourcetraildb_d01c6fe4bdcf0ab5(swig_intgo arg1, swig_intgo arg2, swig_intgo arg3, swig_intgo arg4, swig_intgo arg5, swig_intgo arg6, swig_intgo arg7);
extern _Bool _wrap_recordQualifierLocation_sourcetraildb_d01c6fe4bdcf0ab5(swig_intgo arg1, swig_intgo arg2, swig_intgo arg3, swig_intgo arg4, swig_intgo arg5, swig_intgo arg6);
extern swig_intgo _wrap_recordFile_sourcetraildb_d01c6fe4bdcf0ab5(swig_type_5 arg1);
extern _Bool _wrap_recordFileLanguage_sourcetraildb_d01c6fe4bdcf0ab5(swig_intgo arg1, swig_type_6 arg2);
extern swig_intgo _wrap_recordLocalSymbol_sourcetraildb_d01c6fe4bdcf0ab5(swig_type_7 arg1);
extern _Bool _wrap_recordLocalSymbolLocation_sourcetraildb_d01c6fe4bdcf0ab5(swig_intgo arg1, swig_intgo arg2, swig_intgo arg3, swig_intgo arg4, swig_intgo arg5, swig_intgo arg6);
extern _Bool _wrap_recordAtomicSourceRange_sourcetraildb_d01c6fe4bdcf0ab5(swig_intgo arg1, swig_intgo arg2, swig_intgo arg3, swig_intgo arg4, swig_intgo arg5);
extern _Bool _wrap_recordError_sourcetraildb_d01c6fe4bdcf0ab5(swig_type_8 arg1, _Bool arg2, swig_intgo arg3, swig_intgo arg4, swig_intgo arg5, swig_intgo arg6, swig_intgo arg7);
#undef intgo
*/
import "C"

import "unsafe"
import _ "runtime/cgo"
import "sync"


type _ unsafe.Pointer



var Swig_escape_always_false bool
var Swig_escape_val interface{}


type _swig_fnptr *byte
type _swig_memberptr *byte


type _ sync.Mutex


type swig_gostring struct { p uintptr; n int }
func swigCopyString(s string) string {
  p := *(*swig_gostring)(unsafe.Pointer(&s))
  r := string((*[0x7fffffff]byte)(unsafe.Pointer(p.p))[:p.n])
  Swig_free(p.p)
  return r
}

func Swig_free(arg1 uintptr) {
	_swig_i_0 := arg1
	C._wrap_Swig_free_sourcetraildb_d01c6fe4bdcf0ab5(C.uintptr_t(_swig_i_0))
}

func Swig_malloc(arg1 int) (_swig_ret uintptr) {
	var swig_r uintptr
	_swig_i_0 := arg1
	swig_r = (uintptr)(C._wrap_Swig_malloc_sourcetraildb_d01c6fe4bdcf0ab5(C.swig_intgo(_swig_i_0)))
	return swig_r
}

type DefinitionKind int
func _swig_getDEFINITION_IMPLICIT() (_swig_ret DefinitionKind) {
	var swig_r DefinitionKind
	swig_r = (DefinitionKind)(C._wrap_DEFINITION_IMPLICIT_sourcetraildb_d01c6fe4bdcf0ab5())
	return swig_r
}

var DEFINITION_IMPLICIT DefinitionKind = _swig_getDEFINITION_IMPLICIT()
func _swig_getDEFINITION_EXPLICIT() (_swig_ret DefinitionKind) {
	var swig_r DefinitionKind
	swig_r = (DefinitionKind)(C._wrap_DEFINITION_EXPLICIT_sourcetraildb_d01c6fe4bdcf0ab5())
	return swig_r
}

var DEFINITION_EXPLICIT DefinitionKind = _swig_getDEFINITION_EXPLICIT()
type SymbolKind int
func _swig_getSYMBOL_TYPE() (_swig_ret SymbolKind) {
	var swig_r SymbolKind
	swig_r = (SymbolKind)(C._wrap_SYMBOL_TYPE_sourcetraildb_d01c6fe4bdcf0ab5())
	return swig_r
}

var SYMBOL_TYPE SymbolKind = _swig_getSYMBOL_TYPE()
func _swig_getSYMBOL_BUILTIN_TYPE() (_swig_ret SymbolKind) {
	var swig_r SymbolKind
	swig_r = (SymbolKind)(C._wrap_SYMBOL_BUILTIN_TYPE_sourcetraildb_d01c6fe4bdcf0ab5())
	return swig_r
}

var SYMBOL_BUILTIN_TYPE SymbolKind = _swig_getSYMBOL_BUILTIN_TYPE()
func _swig_getSYMBOL_MODULE() (_swig_ret SymbolKind) {
	var swig_r SymbolKind
	swig_r = (SymbolKind)(C._wrap_SYMBOL_MODULE_sourcetraildb_d01c6fe4bdcf0ab5())
	return swig_r
}

var SYMBOL_MODULE SymbolKind = _swig_getSYMBOL_MODULE()
func _swig_getSYMBOL_NAMESPACE() (_swig_ret SymbolKind) {
	var swig_r SymbolKind
	swig_r = (SymbolKind)(C._wrap_SYMBOL_NAMESPACE_sourcetraildb_d01c6fe4bdcf0ab5())
	return swig_r
}

var SYMBOL_NAMESPACE SymbolKind = _swig_getSYMBOL_NAMESPACE()
func _swig_getSYMBOL_PACKAGE() (_swig_ret SymbolKind) {
	var swig_r SymbolKind
	swig_r = (SymbolKind)(C._wrap_SYMBOL_PACKAGE_sourcetraildb_d01c6fe4bdcf0ab5())
	return swig_r
}

var SYMBOL_PACKAGE SymbolKind = _swig_getSYMBOL_PACKAGE()
func _swig_getSYMBOL_STRUCT() (_swig_ret SymbolKind) {
	var swig_r SymbolKind
	swig_r = (SymbolKind)(C._wrap_SYMBOL_STRUCT_sourcetraildb_d01c6fe4bdcf0ab5())
	return swig_r
}

var SYMBOL_STRUCT SymbolKind = _swig_getSYMBOL_STRUCT()
func _swig_getSYMBOL_CLASS() (_swig_ret SymbolKind) {
	var swig_r SymbolKind
	swig_r = (SymbolKind)(C._wrap_SYMBOL_CLASS_sourcetraildb_d01c6fe4bdcf0ab5())
	return swig_r
}

var SYMBOL_CLASS SymbolKind = _swig_getSYMBOL_CLASS()
func _swig_getSYMBOL_INTERFACE() (_swig_ret SymbolKind) {
	var swig_r SymbolKind
	swig_r = (SymbolKind)(C._wrap_SYMBOL_INTERFACE_sourcetraildb_d01c6fe4bdcf0ab5())
	return swig_r
}

var SYMBOL_INTERFACE SymbolKind = _swig_getSYMBOL_INTERFACE()
func _swig_getSYMBOL_ANNOTATION() (_swig_ret SymbolKind) {
	var swig_r SymbolKind
	swig_r = (SymbolKind)(C._wrap_SYMBOL_ANNOTATION_sourcetraildb_d01c6fe4bdcf0ab5())
	return swig_r
}

var SYMBOL_ANNOTATION SymbolKind = _swig_getSYMBOL_ANNOTATION()
func _swig_getSYMBOL_GLOBAL_VARIABLE() (_swig_ret SymbolKind) {
	var swig_r SymbolKind
	swig_r = (SymbolKind)(C._wrap_SYMBOL_GLOBAL_VARIABLE_sourcetraildb_d01c6fe4bdcf0ab5())
	return swig_r
}

var SYMBOL_GLOBAL_VARIABLE SymbolKind = _swig_getSYMBOL_GLOBAL_VARIABLE()
func _swig_getSYMBOL_FIELD() (_swig_ret SymbolKind) {
	var swig_r SymbolKind
	swig_r = (SymbolKind)(C._wrap_SYMBOL_FIELD_sourcetraildb_d01c6fe4bdcf0ab5())
	return swig_r
}

var SYMBOL_FIELD SymbolKind = _swig_getSYMBOL_FIELD()
func _swig_getSYMBOL_FUNCTION() (_swig_ret SymbolKind) {
	var swig_r SymbolKind
	swig_r = (SymbolKind)(C._wrap_SYMBOL_FUNCTION_sourcetraildb_d01c6fe4bdcf0ab5())
	return swig_r
}

var SYMBOL_FUNCTION SymbolKind = _swig_getSYMBOL_FUNCTION()
func _swig_getSYMBOL_METHOD() (_swig_ret SymbolKind) {
	var swig_r SymbolKind
	swig_r = (SymbolKind)(C._wrap_SYMBOL_METHOD_sourcetraildb_d01c6fe4bdcf0ab5())
	return swig_r
}

var SYMBOL_METHOD SymbolKind = _swig_getSYMBOL_METHOD()
func _swig_getSYMBOL_ENUM() (_swig_ret SymbolKind) {
	var swig_r SymbolKind
	swig_r = (SymbolKind)(C._wrap_SYMBOL_ENUM_sourcetraildb_d01c6fe4bdcf0ab5())
	return swig_r
}

var SYMBOL_ENUM SymbolKind = _swig_getSYMBOL_ENUM()
func _swig_getSYMBOL_ENUM_CONSTANT() (_swig_ret SymbolKind) {
	var swig_r SymbolKind
	swig_r = (SymbolKind)(C._wrap_SYMBOL_ENUM_CONSTANT_sourcetraildb_d01c6fe4bdcf0ab5())
	return swig_r
}

var SYMBOL_ENUM_CONSTANT SymbolKind = _swig_getSYMBOL_ENUM_CONSTANT()
func _swig_getSYMBOL_TYPEDEF() (_swig_ret SymbolKind) {
	var swig_r SymbolKind
	swig_r = (SymbolKind)(C._wrap_SYMBOL_TYPEDEF_sourcetraildb_d01c6fe4bdcf0ab5())
	return swig_r
}

var SYMBOL_TYPEDEF SymbolKind = _swig_getSYMBOL_TYPEDEF()
func _swig_getSYMBOL_TYPE_PARAMETER() (_swig_ret SymbolKind) {
	var swig_r SymbolKind
	swig_r = (SymbolKind)(C._wrap_SYMBOL_TYPE_PARAMETER_sourcetraildb_d01c6fe4bdcf0ab5())
	return swig_r
}

var SYMBOL_TYPE_PARAMETER SymbolKind = _swig_getSYMBOL_TYPE_PARAMETER()
func _swig_getSYMBOL_MACRO() (_swig_ret SymbolKind) {
	var swig_r SymbolKind
	swig_r = (SymbolKind)(C._wrap_SYMBOL_MACRO_sourcetraildb_d01c6fe4bdcf0ab5())
	return swig_r
}

var SYMBOL_MACRO SymbolKind = _swig_getSYMBOL_MACRO()
func _swig_getSYMBOL_UNION() (_swig_ret SymbolKind) {
	var swig_r SymbolKind
	swig_r = (SymbolKind)(C._wrap_SYMBOL_UNION_sourcetraildb_d01c6fe4bdcf0ab5())
	return swig_r
}

var SYMBOL_UNION SymbolKind = _swig_getSYMBOL_UNION()
type ReferenceKind int
func _swig_getREFERENCE_TYPE_USAGE() (_swig_ret ReferenceKind) {
	var swig_r ReferenceKind
	swig_r = (ReferenceKind)(C._wrap_REFERENCE_TYPE_USAGE_sourcetraildb_d01c6fe4bdcf0ab5())
	return swig_r
}

var REFERENCE_TYPE_USAGE ReferenceKind = _swig_getREFERENCE_TYPE_USAGE()
func _swig_getREFERENCE_USAGE() (_swig_ret ReferenceKind) {
	var swig_r ReferenceKind
	swig_r = (ReferenceKind)(C._wrap_REFERENCE_USAGE_sourcetraildb_d01c6fe4bdcf0ab5())
	return swig_r
}

var REFERENCE_USAGE ReferenceKind = _swig_getREFERENCE_USAGE()
func _swig_getREFERENCE_CALL() (_swig_ret ReferenceKind) {
	var swig_r ReferenceKind
	swig_r = (ReferenceKind)(C._wrap_REFERENCE_CALL_sourcetraildb_d01c6fe4bdcf0ab5())
	return swig_r
}

var REFERENCE_CALL ReferenceKind = _swig_getREFERENCE_CALL()
func _swig_getREFERENCE_INHERITANCE() (_swig_ret ReferenceKind) {
	var swig_r ReferenceKind
	swig_r = (ReferenceKind)(C._wrap_REFERENCE_INHERITANCE_sourcetraildb_d01c6fe4bdcf0ab5())
	return swig_r
}

var REFERENCE_INHERITANCE ReferenceKind = _swig_getREFERENCE_INHERITANCE()
func _swig_getREFERENCE_OVERRIDE() (_swig_ret ReferenceKind) {
	var swig_r ReferenceKind
	swig_r = (ReferenceKind)(C._wrap_REFERENCE_OVERRIDE_sourcetraildb_d01c6fe4bdcf0ab5())
	return swig_r
}

var REFERENCE_OVERRIDE ReferenceKind = _swig_getREFERENCE_OVERRIDE()
func _swig_getREFERENCE_TYPE_ARGUMENT() (_swig_ret ReferenceKind) {
	var swig_r ReferenceKind
	swig_r = (ReferenceKind)(C._wrap_REFERENCE_TYPE_ARGUMENT_sourcetraildb_d01c6fe4bdcf0ab5())
	return swig_r
}

var REFERENCE_TYPE_ARGUMENT ReferenceKind = _swig_getREFERENCE_TYPE_ARGUMENT()
func _swig_getREFERENCE_TEMPLATE_SPECIALIZATION() (_swig_ret ReferenceKind) {
	var swig_r ReferenceKind
	swig_r = (ReferenceKind)(C._wrap_REFERENCE_TEMPLATE_SPECIALIZATION_sourcetraildb_d01c6fe4bdcf0ab5())
	return swig_r
}

var REFERENCE_TEMPLATE_SPECIALIZATION ReferenceKind = _swig_getREFERENCE_TEMPLATE_SPECIALIZATION()
func _swig_getREFERENCE_INCLUDE() (_swig_ret ReferenceKind) {
	var swig_r ReferenceKind
	swig_r = (ReferenceKind)(C._wrap_REFERENCE_INCLUDE_sourcetraildb_d01c6fe4bdcf0ab5())
	return swig_r
}

var REFERENCE_INCLUDE ReferenceKind = _swig_getREFERENCE_INCLUDE()
func _swig_getREFERENCE_IMPORT() (_swig_ret ReferenceKind) {
	var swig_r ReferenceKind
	swig_r = (ReferenceKind)(C._wrap_REFERENCE_IMPORT_sourcetraildb_d01c6fe4bdcf0ab5())
	return swig_r
}

var REFERENCE_IMPORT ReferenceKind = _swig_getREFERENCE_IMPORT()
func _swig_getREFERENCE_MACRO_USAGE() (_swig_ret ReferenceKind) {
	var swig_r ReferenceKind
	swig_r = (ReferenceKind)(C._wrap_REFERENCE_MACRO_USAGE_sourcetraildb_d01c6fe4bdcf0ab5())
	return swig_r
}

var REFERENCE_MACRO_USAGE ReferenceKind = _swig_getREFERENCE_MACRO_USAGE()
func _swig_getREFERENCE_ANNOTATION_USAGE() (_swig_ret ReferenceKind) {
	var swig_r ReferenceKind
	swig_r = (ReferenceKind)(C._wrap_REFERENCE_ANNOTATION_USAGE_sourcetraildb_d01c6fe4bdcf0ab5())
	return swig_r
}

var REFERENCE_ANNOTATION_USAGE ReferenceKind = _swig_getREFERENCE_ANNOTATION_USAGE()
func GetVersionString() (_swig_ret string) {
	var swig_r string
	swig_r_p := C._wrap_getVersionString_sourcetraildb_d01c6fe4bdcf0ab5()
	swig_r = *(*string)(unsafe.Pointer(&swig_r_p))
	var swig_r_1 string
 swig_r_1 = swigCopyString(swig_r) 
	return swig_r_1
}

func GetSupportedDatabaseVersion() (_swig_ret int) {
	var swig_r int
	swig_r = (int)(C._wrap_getSupportedDatabaseVersion_sourcetraildb_d01c6fe4bdcf0ab5())
	return swig_r
}

func GetLastError() (_swig_ret string) {
	var swig_r string
	swig_r_p := C._wrap_getLastError_sourcetraildb_d01c6fe4bdcf0ab5()
	swig_r = *(*string)(unsafe.Pointer(&swig_r_p))
	var swig_r_1 string
 swig_r_1 = swigCopyString(swig_r) 
	return swig_r_1
}

func ClearLastError() {
	C._wrap_clearLastError_sourcetraildb_d01c6fe4bdcf0ab5()
}

func Open(arg1 string) (_swig_ret bool) {
	var swig_r bool
	_swig_i_0 := arg1
	swig_r = (bool)(C._wrap_open_sourcetraildb_d01c6fe4bdcf0ab5(*(*C.swig_type_3)(unsafe.Pointer(&_swig_i_0))))
	if Swig_escape_always_false {
		Swig_escape_val = arg1
	}
	return swig_r
}

func Close() (_swig_ret bool) {
	var swig_r bool
	swig_r = (bool)(C._wrap_close_sourcetraildb_d01c6fe4bdcf0ab5())
	return swig_r
}

func Clear() (_swig_ret bool) {
	var swig_r bool
	swig_r = (bool)(C._wrap_clear_sourcetraildb_d01c6fe4bdcf0ab5())
	return swig_r
}

func IsEmpty() (_swig_ret bool) {
	var swig_r bool
	swig_r = (bool)(C._wrap_isEmpty_sourcetraildb_d01c6fe4bdcf0ab5())
	return swig_r
}

func IsCompatible() (_swig_ret bool) {
	var swig_r bool
	swig_r = (bool)(C._wrap_isCompatible_sourcetraildb_d01c6fe4bdcf0ab5())
	return swig_r
}

func GetLoadedDatabaseVersion() (_swig_ret int) {
	var swig_r int
	swig_r = (int)(C._wrap_getLoadedDatabaseVersion_sourcetraildb_d01c6fe4bdcf0ab5())
	return swig_r
}

func BeginTransaction() (_swig_ret bool) {
	var swig_r bool
	swig_r = (bool)(C._wrap_beginTransaction_sourcetraildb_d01c6fe4bdcf0ab5())
	return swig_r
}

func CommitTransaction() (_swig_ret bool) {
	var swig_r bool
	swig_r = (bool)(C._wrap_commitTransaction_sourcetraildb_d01c6fe4bdcf0ab5())
	return swig_r
}

func RollbackTransaction() (_swig_ret bool) {
	var swig_r bool
	swig_r = (bool)(C._wrap_rollbackTransaction_sourcetraildb_d01c6fe4bdcf0ab5())
	return swig_r
}

func OptimizeDatabaseMemory() (_swig_ret bool) {
	var swig_r bool
	swig_r = (bool)(C._wrap_optimizeDatabaseMemory_sourcetraildb_d01c6fe4bdcf0ab5())
	return swig_r
}

func RecordSymbol(arg1 string) (_swig_ret int) {
	var swig_r int
	_swig_i_0 := arg1
	swig_r = (int)(C._wrap_recordSymbol_sourcetraildb_d01c6fe4bdcf0ab5(*(*C.swig_type_4)(unsafe.Pointer(&_swig_i_0))))
	if Swig_escape_always_false {
		Swig_escape_val = arg1
	}
	return swig_r
}

func RecordSymbolDefinitionKind(arg1 int, arg2 DefinitionKind) (_swig_ret bool) {
	var swig_r bool
	_swig_i_0 := arg1
	_swig_i_1 := arg2
	swig_r = (bool)(C._wrap_recordSymbolDefinitionKind_sourcetraildb_d01c6fe4bdcf0ab5(C.swig_intgo(_swig_i_0), C.swig_intgo(_swig_i_1)))
	return swig_r
}

func RecordSymbolKind(arg1 int, arg2 SymbolKind) (_swig_ret bool) {
	var swig_r bool
	_swig_i_0 := arg1
	_swig_i_1 := arg2
	swig_r = (bool)(C._wrap_recordSymbolKind_sourcetraildb_d01c6fe4bdcf0ab5(C.swig_intgo(_swig_i_0), C.swig_intgo(_swig_i_1)))
	return swig_r
}

func RecordSymbolLocation(arg1 int, arg2 int, arg3 int, arg4 int, arg5 int, arg6 int) (_swig_ret bool) {
	var swig_r bool
	_swig_i_0 := arg1
	_swig_i_1 := arg2
	_swig_i_2 := arg3
	_swig_i_3 := arg4
	_swig_i_4 := arg5
	_swig_i_5 := arg6
	swig_r = (bool)(C._wrap_recordSymbolLocation_sourcetraildb_d01c6fe4bdcf0ab5(C.swig_intgo(_swig_i_0), C.swig_intgo(_swig_i_1), C.swig_intgo(_swig_i_2), C.swig_intgo(_swig_i_3), C.swig_intgo(_swig_i_4), C.swig_intgo(_swig_i_5)))
	return swig_r
}

func RecordSymbolScopeLocation(arg1 int, arg2 int, arg3 int, arg4 int, arg5 int, arg6 int) (_swig_ret bool) {
	var swig_r bool
	_swig_i_0 := arg1
	_swig_i_1 := arg2
	_swig_i_2 := arg3
	_swig_i_3 := arg4
	_swig_i_4 := arg5
	_swig_i_5 := arg6
	swig_r = (bool)(C._wrap_recordSymbolScopeLocation_sourcetraildb_d01c6fe4bdcf0ab5(C.swig_intgo(_swig_i_0), C.swig_intgo(_swig_i_1), C.swig_intgo(_swig_i_2), C.swig_intgo(_swig_i_3), C.swig_intgo(_swig_i_4), C.swig_intgo(_swig_i_5)))
	return swig_r
}

func RecordSymbolSignatureLocation(arg1 int, arg2 int, arg3 int, arg4 int, arg5 int, arg6 int) (_swig_ret bool) {
	var swig_r bool
	_swig_i_0 := arg1
	_swig_i_1 := arg2
	_swig_i_2 := arg3
	_swig_i_3 := arg4
	_swig_i_4 := arg5
	_swig_i_5 := arg6
	swig_r = (bool)(C._wrap_recordSymbolSignatureLocation_sourcetraildb_d01c6fe4bdcf0ab5(C.swig_intgo(_swig_i_0), C.swig_intgo(_swig_i_1), C.swig_intgo(_swig_i_2), C.swig_intgo(_swig_i_3), C.swig_intgo(_swig_i_4), C.swig_intgo(_swig_i_5)))
	return swig_r
}

func RecordReference(arg1 int, arg2 int, arg3 ReferenceKind) (_swig_ret int) {
	var swig_r int
	_swig_i_0 := arg1
	_swig_i_1 := arg2
	_swig_i_2 := arg3
	swig_r = (int)(C._wrap_recordReference_sourcetraildb_d01c6fe4bdcf0ab5(C.swig_intgo(_swig_i_0), C.swig_intgo(_swig_i_1), C.swig_intgo(_swig_i_2)))
	return swig_r
}

func RecordReferenceLocation(arg1 int, arg2 int, arg3 int, arg4 int, arg5 int, arg6 int) (_swig_ret bool) {
	var swig_r bool
	_swig_i_0 := arg1
	_swig_i_1 := arg2
	_swig_i_2 := arg3
	_swig_i_3 := arg4
	_swig_i_4 := arg5
	_swig_i_5 := arg6
	swig_r = (bool)(C._wrap_recordReferenceLocation_sourcetraildb_d01c6fe4bdcf0ab5(C.swig_intgo(_swig_i_0), C.swig_intgo(_swig_i_1), C.swig_intgo(_swig_i_2), C.swig_intgo(_swig_i_3), C.swig_intgo(_swig_i_4), C.swig_intgo(_swig_i_5)))
	return swig_r
}

func RecordReferenceIsAmbiguous(arg1 int) (_swig_ret bool) {
	var swig_r bool
	_swig_i_0 := arg1
	swig_r = (bool)(C._wrap_recordReferenceIsAmbiguous_sourcetraildb_d01c6fe4bdcf0ab5(C.swig_intgo(_swig_i_0)))
	return swig_r
}

func RecordReferenceToUnsolvedSymhol(arg1 int, arg2 ReferenceKind, arg3 int, arg4 int, arg5 int, arg6 int, arg7 int) (_swig_ret int) {
	var swig_r int
	_swig_i_0 := arg1
	_swig_i_1 := arg2
	_swig_i_2 := arg3
	_swig_i_3 := arg4
	_swig_i_4 := arg5
	_swig_i_5 := arg6
	_swig_i_6 := arg7
	swig_r = (int)(C._wrap_recordReferenceToUnsolvedSymhol_sourcetraildb_d01c6fe4bdcf0ab5(C.swig_intgo(_swig_i_0), C.swig_intgo(_swig_i_1), C.swig_intgo(_swig_i_2), C.swig_intgo(_swig_i_3), C.swig_intgo(_swig_i_4), C.swig_intgo(_swig_i_5), C.swig_intgo(_swig_i_6)))
	return swig_r
}

func RecordQualifierLocation(arg1 int, arg2 int, arg3 int, arg4 int, arg5 int, arg6 int) (_swig_ret bool) {
	var swig_r bool
	_swig_i_0 := arg1
	_swig_i_1 := arg2
	_swig_i_2 := arg3
	_swig_i_3 := arg4
	_swig_i_4 := arg5
	_swig_i_5 := arg6
	swig_r = (bool)(C._wrap_recordQualifierLocation_sourcetraildb_d01c6fe4bdcf0ab5(C.swig_intgo(_swig_i_0), C.swig_intgo(_swig_i_1), C.swig_intgo(_swig_i_2), C.swig_intgo(_swig_i_3), C.swig_intgo(_swig_i_4), C.swig_intgo(_swig_i_5)))
	return swig_r
}

func RecordFile(arg1 string) (_swig_ret int) {
	var swig_r int
	_swig_i_0 := arg1
	swig_r = (int)(C._wrap_recordFile_sourcetraildb_d01c6fe4bdcf0ab5(*(*C.swig_type_5)(unsafe.Pointer(&_swig_i_0))))
	if Swig_escape_always_false {
		Swig_escape_val = arg1
	}
	return swig_r
}

func RecordFileLanguage(arg1 int, arg2 string) (_swig_ret bool) {
	var swig_r bool
	_swig_i_0 := arg1
	_swig_i_1 := arg2
	swig_r = (bool)(C._wrap_recordFileLanguage_sourcetraildb_d01c6fe4bdcf0ab5(C.swig_intgo(_swig_i_0), *(*C.swig_type_6)(unsafe.Pointer(&_swig_i_1))))
	if Swig_escape_always_false {
		Swig_escape_val = arg2
	}
	return swig_r
}

func RecordLocalSymbol(arg1 string) (_swig_ret int) {
	var swig_r int
	_swig_i_0 := arg1
	swig_r = (int)(C._wrap_recordLocalSymbol_sourcetraildb_d01c6fe4bdcf0ab5(*(*C.swig_type_7)(unsafe.Pointer(&_swig_i_0))))
	if Swig_escape_always_false {
		Swig_escape_val = arg1
	}
	return swig_r
}

func RecordLocalSymbolLocation(arg1 int, arg2 int, arg3 int, arg4 int, arg5 int, arg6 int) (_swig_ret bool) {
	var swig_r bool
	_swig_i_0 := arg1
	_swig_i_1 := arg2
	_swig_i_2 := arg3
	_swig_i_3 := arg4
	_swig_i_4 := arg5
	_swig_i_5 := arg6
	swig_r = (bool)(C._wrap_recordLocalSymbolLocation_sourcetraildb_d01c6fe4bdcf0ab5(C.swig_intgo(_swig_i_0), C.swig_intgo(_swig_i_1), C.swig_intgo(_swig_i_2), C.swig_intgo(_swig_i_3), C.swig_intgo(_swig_i_4), C.swig_intgo(_swig_i_5)))
	return swig_r
}

func RecordAtomicSourceRange(arg1 int, arg2 int, arg3 int, arg4 int, arg5 int) (_swig_ret bool) {
	var swig_r bool
	_swig_i_0 := arg1
	_swig_i_1 := arg2
	_swig_i_2 := arg3
	_swig_i_3 := arg4
	_swig_i_4 := arg5
	swig_r = (bool)(C._wrap_recordAtomicSourceRange_sourcetraildb_d01c6fe4bdcf0ab5(C.swig_intgo(_swig_i_0), C.swig_intgo(_swig_i_1), C.swig_intgo(_swig_i_2), C.swig_intgo(_swig_i_3), C.swig_intgo(_swig_i_4)))
	return swig_r
}

func RecordError(arg1 string, arg2 bool, arg3 int, arg4 int, arg5 int, arg6 int, arg7 int) (_swig_ret bool) {
	var swig_r bool
	_swig_i_0 := arg1
	_swig_i_1 := arg2
	_swig_i_2 := arg3
	_swig_i_3 := arg4
	_swig_i_4 := arg5
	_swig_i_5 := arg6
	_swig_i_6 := arg7
	swig_r = (bool)(C._wrap_recordError_sourcetraildb_d01c6fe4bdcf0ab5(*(*C.swig_type_8)(unsafe.Pointer(&_swig_i_0)), C._Bool(_swig_i_1), C.swig_intgo(_swig_i_2), C.swig_intgo(_swig_i_3), C.swig_intgo(_swig_i_4), C.swig_intgo(_swig_i_5), C.swig_intgo(_swig_i_6)))
	if Swig_escape_always_false {
		Swig_escape_val = arg1
	}
	return swig_r
}


